### ISSUE TITLE
Problems with BBB-Meetings

### ISSUE THREAD

**Issue by kevinbischof** [corona-school/backend#132]
See description in commit https://github.com/corona-school/backend/commit/68e23397a5f6d0dd3d63968b3f9ecf115898a2b0

Unfortunately there is currently no exact description or documentation of the problem. I suspect that there is an overlap of two actions:
1. the automatic termination of BBB meetings by BBB even after the last user has left a meeting. The time limit is 15 minutes. 
2. The backend fetches all active meetings from BBB every 14 minutes and keeps them in cache.

**Comment by geroembser** [comment]
I still don't know from where exactly the problem came from and it's probably not yet fully fixed. I am in contact with the support team and we're trying to get more details on the problem. But for me it looks like many problems are somehow related to the cache. So I'm really not that deep in BBB's details as you are @kevinbischof but do you think we can omit the cache? This will possibly increase API calls between the backend server and the BBB server, but I think for our use cases this would be totally fine. If we gained stability, we could easily pay a certain price for speed. Would that be a possible approach for more stability?

**Comment by kevinbischof** [comment]
The use of a chache to temporarily store BBB meetings and the generation of meeting-urls from the stored BBB meetings shall be replaced by a database table.
This should solve the problem I described above.
